/* eslint-disable no-use-before-define */
export const resContestGetAll = ({ offset, limit }) => {
  return new Promise((res) =>
    setTimeout(
      () =>
        res({
          code: 0,
          data: {
            total: 16,
            contests: contests.slice(offset, offset + limit),
          },
        }),
      1000,
    ),
  );
};

const contests = [
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1609414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1609414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1609414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-129',
    contest_title: 'Free Contest 129',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
  {
    can_enter: false,
    contest_name: 'free-contest-130',
    contest_title: 'Free Contest 130',
    duration: 10800,
    materials: {
      all_materials_url: '',
      editorial_url: '',
      ranking_url: '',
      solution_url: '',
      statements_url: '',
      test_data_url: '',
    },
    start_time: 1409414200,
    total_participation: 0,
  },
];
